### PR TITLE
Make sure cancelation is not caught

### LINKED ISSUE #5: CancellationToken exception
Cancelling a token often results in an `OperationCanceledException` which *should not* be caught and reprocessed, else the cancellation process won't have an impact.

### PR DESCRIPTION
**Pull request by herecydev**
Resolves #5

### CODE REVIEW

File: src/Rush/MessageSender.cs [hunk 1]
```diff
@@ -39,7 +39,7 @@ public Task SendAsync(T message, CancellationToken cancellationToken)
 			{
 				await operationalChannel.SendAsync(message, cancellationToken).ConfigureAwait(false);
 			}
-			catch (Exception ex)
+			catch (Exception ex) when (ex.GetType() != typeof(OperationCanceledException))
```
Comment (smudge202) [inline src/Rush/MessageSender.cs]: can't decide what's better...

`catch (OperationCanceledException) { }`

or using the inverted filter.
